#encoding: utf-8

user = User.create(email: "pyluftig@gmail.com", password: "password", name: "Paulette Luftig", password_confirmation: "password", admin: true)

user.videos << Video.create(title: "Lounge Music", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=pHfCj8KsgRY" )
user.videos << Video.create(title: "Relax Music", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=p6kE_EW0fTo" )
user.videos << Video.create(title: "Spirit of Meditation", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=YHNrAE8IFUI" )
user.videos << Video.create(title: "Spirits", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=_JgHVlcaQJ0" )
user.videos << Video.create(title: "Music to Relax Your Mind To", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=Tj8p9DofvZA" )
user.videos << Video.create(title: "Meditation Music", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=rljDFfufSCo" )
user.videos << Video.create(title: "Seconds of Beauty", description: "This is just another film to test out what things look like at this point.", url: "https://vimeo.com/32071937" )
user.videos << Video.create(title: "Calm Music", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=TZMoS2QBc8U" )
user.videos << Video.create(title: "Sound Therapy", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=R_K_mMhZrPs" )
user.videos << Video.create(title: "Are You an Imaginal?", description: "They start to create new organizations, to create something more fabulous than the previous system. A system that is much more sustainable.  A system with a higher level of evolution.", url: "http://www.youtube.com/watch?v=7DLokOQZlag", :feature => true )
user.videos << Video.create(title: "Flux", description: "This is just another film to test out what things look like at this point.", url: "https://vimeo.com/15395471" )
user.videos << Video.create(title: "TimeScapes", description: "This is just another film to test out what things look like at this point.", url: "https://vimeo.com/33110953" )
user.videos << Video.create(title: "Inspired Iceland", description: "This is just another film to test out what things look like at this point.", url: "https://vimeo.com/12236680" )
user.videos << Video.create(title: "Snap Your Joy", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=7_XSQfi8cos" )
user.videos << Video.create(title: "Slip and Slide Loop", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=VSDRqV1p63A" )
user.videos << Video.create(title: "Dare to Be Great", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=PiyOF6DW-Qo" )
user.videos << Video.create(title: "Me", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=D4zWBHFCmXM" )
user.videos << Video.create(title: "Philosophy of Joy", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=cbbnj0qQ4s4" )
user.videos << Video.create(title: "Guide to Happiness", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=irornIAQzQY" )
user.videos << Video.create(title: "The Art of Happiness", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=ZvTnNIO1BT0" )

#user.profile = Profile.create(full_name: "Paulette Luftig", blurb: "I am a human... being...")
#user.save

user = User.create(email: "aducker@hotmail.com", password: "password", password_confirmation: "password", admin: true)

["Production Quality", "Radical Creativity", "Communal Effort", "Radical Inclusivity", "Civic Responsibility", "Immediacy"].each do |category|
  Category.create(name: category)
end

rating = Rating.create(video_id: 1, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 1, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 1, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 1, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 1, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 1, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 2, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 2, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 2, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 2, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 2, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 2, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 3, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 3, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 3, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 3, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 3, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 3, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 4, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 4, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 4, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 4, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 4, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 4, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 5, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 5, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 5, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 5, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 5, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 5, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 6, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 6, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 6, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 6, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 6, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 6, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 7, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 7, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 7, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 7, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 7, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 7, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 8, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 8, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 8, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 8, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 8, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 8, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 9, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 9, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 9, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 9, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 9, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 9, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 10, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 10, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 10, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 10, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 10, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 10, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 11, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 11, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 11, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 11, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 11, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 11, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 12, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 12, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 12, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 12, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 12, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 12, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 13, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 13, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 13, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 13, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 13, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 13, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 14, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 14, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 14, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 14, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 14, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 14, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 15, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 15, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 15, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 15, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 15, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 15, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 16, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 16, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 16, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 16, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 16, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 16, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 17, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 17, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 17, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 17, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 17, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 17, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 18, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 18, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 18, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 18, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 18, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 18, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 19, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 19, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 19, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 19, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 19, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 19, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 20, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 20, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 20, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 20, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 20, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 20, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)



