#encoding: utf-8

user = User.create(email: "pyluftig@gmail.com", password: "password", name: "Paulette Luftig", password_confirmation: "password", admin: true)

user.videos << Video.create(title: "Lounge Music", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=pHfCj8KsgRY" )
user.videos << Video.create(title: "Relax Music", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=p6kE_EW0fTo" )
user.videos << Video.create(title: "Spirit of Meditation", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=YHNrAE8IFUI" )
user.videos << Video.create(title: "Spirits", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=_JgHVlcaQJ0" )
user.videos << Video.create(title: "Music to Relax Your Mind To", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=Tj8p9DofvZA" )
user.videos << Video.create(title: "Meditation Music", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=rljDFfufSCo" )
user.videos << Video.create(title: "Seconds of Beauty", description: "This is just another film to test out what things look like at this point.", url: "https://vimeo.com/32071937" )
user.videos << Video.create(title: "Calm Music", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=TZMoS2QBc8U" )
user.videos << Video.create(title: "Sound Therapy", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=R_K_mMhZrPs" )
user.videos << Video.create(title: "Are You an Imaginal?", description: "They start to create new organizations, to create something more fabulous than the previous system. A system that is much more sustainable.  A system with a higher level of evolution.", url: "http://www.youtube.com/watch?v=7DLokOQZlag", :feature => true )
user.videos << Video.create(title: "Flux", description: "This is just another film to test out what things look like at this point.", url: "https://vimeo.com/15395471" )
user.videos << Video.create(title: "TimeScapes", description: "This is just another film to test out what things look like at this point.", url: "https://vimeo.com/33110953" )
user.videos << Video.create(title: "Inspired Iceland", description: "This is just another film to test out what things look like at this point.", url: "https://vimeo.com/12236680" )
user.videos << Video.create(title: "Snap Your Joy", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=7_XSQfi8cos" )
user.videos << Video.create(title: "Slip and Slide Loop", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=VSDRqV1p63A" )
user.videos << Video.create(title: "Dare to Be Great", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=PiyOF6DW-Qo" )
user.videos << Video.create(title: "Me", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=D4zWBHFCmXM" )
user.videos << Video.create(title: "Philosophy of Joy", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=cbbnj0qQ4s4" )
user.videos << Video.create(title: "Guide to Happiness", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=irornIAQzQY" )
user.videos << Video.create(title: "The Art of Happiness", description: "This is just another film to test out what things look like at this point.", url: "http://www.youtube.com/watch?v=ZvTnNIO1BT0" )

#user.profile = Profile.create(full_name: "Paulette Luftig", blurb: "I am a human... being...")
#user.save

user = User.create(email: "aducker@hotmail.com", password: "password", password_confirmation: "password", admin: true)

Category.create(name: "Production Quality", description: "We value attention to detail, and care for final the product. We honor the work that has been carefully and lovingly produced. We celebrate those who demonstrate this kind of care and commitment to quality.", alternates: '', sort_order: 1)
Category.create(name: "Radical Creativity", description: "We celebrate those who step beyond the vulnerabilities of being exposed, and expressing their unique gifts to the world. We honor who inspire us to radically express our own selves.", alternates: '', sort_order: 2)
Category.create(name: "Communal Effort", description: "We value creative cooperation and collaboration. We celebrate those who demonstrate to us the power of coming together. We honor the work that requires communal effort to produce.", alternates: '', sort_order: 3)
Category.create(name: "Radical Inclusivity", description: "No matter what, we welcome the stranger. There is no contrast or quality by which we choose to exclude others. We enter into a global family that transcends any identifier, and we celebrate the media and heroes that demonstrate that quality.", alternates: '', sort_order: 4)
Category.create(name: "Civic Responsibility", description: "We value civil society. We celebrate those who that demonstrate the individual or collective capacity to benefit our community. Whether local, regional, national, and international community we honor the ethic of responsibility to others.", alternates: '', sort_order: 5)
Category.create(name: "Immediacy", description: "We seek to overcome barriers that stand between us and a recognition of our inner selves, the reality of those around us, participation in society, and contact with a natural world exceeding human powers. We celebrate those who take us beyond those barriers.", alternates: '', sort_order: 6)

rating = Rating.create(video_id: 1, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 1, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 1, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 1, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 1, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 1, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 2, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 2, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 2, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 2, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 2, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 2, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 3, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 3, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 3, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 3, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 3, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 3, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 4, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 4, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 4, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 4, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 4, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 4, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 5, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 5, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 5, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 5, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 5, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 5, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 6, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 6, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 6, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 6, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 6, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 6, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 7, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 7, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 7, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 7, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 7, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 7, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 8, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 8, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 8, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 8, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 8, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 8, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 9, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 9, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 9, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 9, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 9, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 9, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 10, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 10, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 10, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 10, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 10, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 10, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 11, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 11, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 11, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 11, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 11, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 11, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 12, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 12, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 12, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 12, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 12, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 12, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 13, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 13, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 13, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 13, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 13, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 13, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 14, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 14, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 14, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 14, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 14, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 14, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 15, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 15, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 15, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 15, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 15, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 15, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 16, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 16, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 16, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 16, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 16, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 16, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 17, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 17, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 17, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 17, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 17, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 17, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 18, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 18, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 18, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 18, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 18, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 18, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 19, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 19, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 19, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 19, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 19, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 19, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)

rating = Rating.create(video_id: 20, category_id: 1, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 20, category_id: 2, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 20, category_id: 3, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 20, category_id: 4, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 20, category_id: 5, num_stars: (1+rand(5)))
Average.update(rating)
rating = Rating.create(video_id: 20, category_id: 6, num_stars: (1+rand(5)))
Average.update(rating)



